name: chap_chap
description: Application de rechargement mobile pour les utilisateurs en Côte d'Ivoire
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  google_fonts: ^5.1.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration pour les icônes de l'application
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - logo.png
    - forfaits.json
    - assets/images/
    - assets/data/
